<?php

/*
 * Accreditations and training partners, as supplied by CompuBase (5 Oct 2026).
 * Logos are in images/partners/{slug}.png. A badge is only set where the partner's own
 * logo states the status (for example "Official Test Centre"); otherwise it is left empty.
 */
return [
    'groups' => [
        'accreditation' => [
            'en' => 'Accreditation and official test centres',
            'ar' => 'الاعتمادات ومراكز الاختبار الرسمية',
            'intro_en' => 'Licensed in Abu Dhabi and approved to run internationally recognised English, IT and professional certification exams.',
            'intro_ar' => 'مرخّصون في أبوظبي ومعتمدون لعقد امتحانات اللغة الإنجليزية وتقنية المعلومات والشهادات المهنية المعترف بها دولياً.',
        ],
        'technology' => [
            'en' => 'Technology and cloud partners',
            'ar' => 'شركاء التقنية والحوسبة السحابية',
            'intro_en' => 'Authorised training from the vendors behind the platforms UAE organisations run on.',
            'intro_ar' => 'تدريب معتمد من الشركات المطوّرة للمنصات التي تعتمد عليها المؤسسات في الإمارات.',
        ],
        'security' => [
            'en' => 'Cyber security and governance partners',
            'ar' => 'شركاء الأمن السيبراني والحوكمة',
            'intro_en' => 'Official training partners for the leading security, audit and governance certifications.',
            'intro_ar' => 'شركاء تدريب رسميون لأبرز شهادات الأمن والتدقيق والحوكمة.',
        ],
    ],

    'partners' => [
        ['slug' => 'actvet', 'group' => 'accreditation', 'en' => 'ACTVET', 'ar' => 'أكتفيت',
            'badge_en' => '', 'badge_ar' => '',
            'desc_en' => 'Abu Dhabi Centre for Technical and Vocational Education and Training.',
            'desc_ar' => 'مركز أبوظبي للتعليم والتدريب التقني والمهني.'],
        ['slug' => 'british-council-ielts', 'group' => 'accreditation', 'en' => 'British Council – IELTS', 'ar' => 'المجلس الثقافي البريطاني – آيلتس',
            'badge_en' => 'Official Test Centre', 'badge_ar' => 'مركز اختبار رسمي',
            'desc_en' => 'IELTS, the International English Language Testing System, delivered with the British Council.',
            'desc_ar' => 'اختبار آيلتس الدولي للغة الإنجليزية بالتعاون مع المجلس الثقافي البريطاني.'],
        ['slug' => 'pearson-vue', 'group' => 'accreditation', 'en' => 'Pearson VUE', 'ar' => 'بيرسون في يو إي',
            'badge_en' => 'Authorized Test Center', 'badge_ar' => 'مركز اختبار معتمد',
            'desc_en' => 'Computer-based exams for IT and professional certifications.',
            'desc_ar' => 'امتحانات محوسبة لشهادات تقنية المعلومات والشهادات المهنية.'],
        ['slug' => 'pearson-pte', 'group' => 'accreditation', 'en' => 'Pearson PTE', 'ar' => 'بيرسون PTE',
            'badge_en' => '', 'badge_ar' => '',
            'desc_en' => 'Pearson Test of English, for study, work and migration.',
            'desc_ar' => 'اختبار بيرسون للغة الإنجليزية للدراسة والعمل والهجرة.'],
        ['slug' => 'psi', 'group' => 'accreditation', 'en' => 'PSI', 'ar' => 'PSI',
            'badge_en' => '', 'badge_ar' => '',
            'desc_en' => 'Certification and licensing exams for professional bodies worldwide.',
            'desc_ar' => 'امتحانات الشهادات والترخيص لهيئات مهنية حول العالم.'],
        ['slug' => 'icdl', 'group' => 'accreditation', 'en' => 'ICDL', 'ar' => 'الرخصة الدولية لقيادة الحاسوب',
            'badge_en' => 'The Digital Skills Standard', 'badge_ar' => 'معيار المهارات الرقمية',
            'desc_en' => 'International Certification of Digital Literacy.',
            'desc_ar' => 'الشهادة الدولية للمهارات الرقمية.'],

        ['slug' => 'microsoft', 'group' => 'technology', 'en' => 'Microsoft', 'ar' => 'مايكروسوفت',
            'badge_en' => '', 'badge_ar' => '',
            'desc_en' => 'Azure, Microsoft 365, Power BI and Windows Server training.',
            'desc_ar' => 'تدريب Azure وMicrosoft 365 وPower BI وWindows Server.'],
        ['slug' => 'aws', 'group' => 'technology', 'en' => 'AWS', 'ar' => 'أمازون ويب سيرفسز',
            'badge_en' => 'Partner · Advanced Tier Training', 'badge_ar' => 'شريك · المستوى المتقدم للتدريب',
            'desc_en' => 'Amazon Web Services cloud training and certification.',
            'desc_ar' => 'تدريب وشهادات خدمات أمازون السحابية.'],
        ['slug' => 'google-cloud', 'group' => 'technology', 'en' => 'Google Cloud', 'ar' => 'جوجل كلاود',
            'badge_en' => 'Partner', 'badge_ar' => 'شريك',
            'desc_en' => 'Google Cloud infrastructure, data and AI training.',
            'desc_ar' => 'تدريب البنية التحتية والبيانات والذكاء الاصطناعي على جوجل كلاود.'],
        ['slug' => 'netapp', 'group' => 'technology', 'en' => 'NetApp', 'ar' => 'نت آب',
            'badge_en' => 'Partner · Authorized Learning', 'badge_ar' => 'شريك · تعلّم معتمد',
            'desc_en' => 'Data storage and hybrid cloud data management.',
            'desc_ar' => 'تخزين البيانات وإدارتها في السحابة الهجينة.'],
        ['slug' => 'nutanix', 'group' => 'technology', 'en' => 'Nutanix', 'ar' => 'نيوتانكس',
            'badge_en' => 'Authorized Training Partner', 'badge_ar' => 'شريك تدريب معتمد',
            'desc_en' => 'Hyperconverged infrastructure and hybrid multicloud.',
            'desc_ar' => 'البنية التحتية فائقة التقارب والسحابة المتعددة الهجينة.'],
        ['slug' => 'databricks', 'group' => 'technology', 'en' => 'Databricks', 'ar' => 'داتابريكس',
            'badge_en' => '', 'badge_ar' => '',
            'desc_en' => 'Data engineering, Apache Spark and lakehouse analytics.',
            'desc_ar' => 'هندسة البيانات وApache Spark وتحليلات بحيرات البيانات.'],
        ['slug' => 'snowflake', 'group' => 'technology', 'en' => 'Snowflake', 'ar' => 'سنوفليك',
            'badge_en' => 'Authorized Training Reseller', 'badge_ar' => 'موزّع تدريب معتمد',
            'desc_en' => 'Cloud data platform and data warehousing.',
            'desc_ar' => 'منصة البيانات السحابية ومستودعات البيانات.'],
        ['slug' => 'trainocate', 'group' => 'technology', 'en' => 'Trainocate', 'ar' => 'ترينوكيت',
            'badge_en' => '', 'badge_ar' => '',
            'desc_en' => 'International IT training and certification provider.',
            'desc_ar' => 'مزوّد دولي للتدريب والشهادات في تقنية المعلومات.'],

        ['slug' => 'isaca', 'group' => 'security', 'en' => 'ISACA', 'ar' => 'إيساكا',
            'badge_en' => 'Accredited Elite Partner', 'badge_ar' => 'شريك نخبة معتمد',
            'desc_en' => 'CISA, CISM, CRISC, CGEIT and COBIT training.',
            'desc_ar' => 'تدريب CISA وCISM وCRISC وCGEIT وCOBIT.'],
        ['slug' => 'isc2', 'group' => 'security', 'en' => 'ISC2', 'ar' => 'ISC2',
            'badge_en' => 'Official Training Partner', 'badge_ar' => 'شريك تدريب رسمي',
            'desc_en' => 'CISSP, CCSP and other cyber security certifications.',
            'desc_ar' => 'شهادات CISSP وCCSP وغيرها من شهادات الأمن السيبراني.'],
        ['slug' => 'palo-alto', 'group' => 'security', 'en' => 'Palo Alto Networks', 'ar' => 'بالو ألتو نتووركس',
            'badge_en' => 'Authorized Training Partner', 'badge_ar' => 'شريك تدريب معتمد',
            'desc_en' => 'Next-generation firewall and network security training.',
            'desc_ar' => 'تدريب جدران الحماية من الجيل التالي وأمن الشبكات.'],
        ['slug' => 'splunk', 'group' => 'security', 'en' => 'Splunk', 'ar' => 'سبلنك',
            'badge_en' => 'Authorized Learning Partner', 'badge_ar' => 'شريك تعلّم معتمد',
            'desc_en' => 'Security monitoring, SIEM and data analytics.',
            'desc_ar' => 'المراقبة الأمنية وأنظمة SIEM وتحليل البيانات.'],
        ['slug' => 'trend-micro', 'group' => 'security', 'en' => 'Trend Micro', 'ar' => 'تريند مايكرو',
            'badge_en' => '', 'badge_ar' => '',
            'desc_en' => 'Endpoint, cloud and network security solutions.',
            'desc_ar' => 'حلول أمن الأجهزة الطرفية والسحابة والشبكات.'],
    ],
];
